/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const CalendarLocale_en_US: typeof import('./src/components/Calender')['CalendarLocale_en_US']
  const CalendarLocale_zh_CN: typeof import('./src/components/Calender')['CalendarLocale_zh_CN']
  const Calender: typeof import('./src/components/Calender')['default']
  const CalenderHeader: typeof import('./src/components/Calender')['CalenderHeader']
  const Component: typeof import('./src/components/MiniCalender')['Component']
  const Context: typeof import('./src/components/Context')['default']
  const CopyToClipboard: typeof import('./src/components/CopyToClipboard')['default']
  const ErrorBoundary: typeof import('./src/components/Suspense')['ErrorBoundary']
  const Father: typeof import('./src/components/Father')['default']
  const Icon: typeof import('./src/components/Icon')['default']
  const IconAdd: typeof import('./src/components/Icon')['IconAdd']
  const IconFont: typeof import('./src/components/Icon')['IconFont']
  const LocaleContext: typeof import('./src/components/Calender')['LocaleContext']
  const Month: typeof import('./src/components/MiniCalender')['Month']
  const MonthCalender: typeof import('./src/components/Calender')['MonthCalender']
  const MutateObserver: typeof import('./src/components/MutationObserver')['MutateObserver']
  const MutationObserver: typeof import('./src/components/MutationObserver')['default']
  const Observer: typeof import('./src/components/Observer')['default']
  const Portal: typeof import('./src/components/Portal')['default']
  const Provider: typeof import('./src/components/Context')['Provider']
  const Space: typeof import('./src/components/Space')['default']
  const SpaceContext: typeof import('./src/components/Space')['SpaceContext']
  const SpaceProvide: typeof import('./src/components/Space')['SpaceProvide']
  const Suspense: typeof import('./src/components/Suspense')['default']
  const Three: typeof import('./src/components/Three')['default']
  const Virtualized: typeof import('./src/components/Virtualized')['default']
  const allLanguages: typeof import('./src/components/Calender')['allLanguages']
  const createFromIconfont: typeof import('./src/components/Icon')['createFromIconfont']
  const createIcon: typeof import('./src/components/Icon')['createIcon']
  const createRef: typeof import('react')['createRef']
  const dnd: typeof import('./src/components/dnd')['default']
  const forwardRef: typeof import('react')['forwardRef']
  const getSize: typeof import('./src/components/Icon')['getSize']
  const jotai: typeof import('./src/components/jotai')['default']
  const lazy: typeof import('react')['lazy']
  const loader: typeof import('./src/components/MiniCalender')['loader']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const tooltip: typeof import('./src/components/tooltip')['default']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMutationObserver: typeof import('./src/components/MutationObserver')['useMutationObserver']
  const useNum: typeof import('./src/components/Context')['useNum']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const weeks: typeof import('./src/components/MiniCalender')['weeks']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Month } from './src/components/MiniCalender'
  import('./src/components/MiniCalender')
}
